### ISSUE TITLE
Transformation no longer works

### ISSUE THREAD

**Issue by aoertel** [MassimoLauria/cnfgen#114]
When I generate ordering principle formulas and then transform them using XORs, e.g.:
```
cnfgen op 10 3 -T xor 2
```
then CNFgen throws a `KeyError`. Generating the ordering principle formula without the transformation works fine.

The problem seems to be with the transformation, as
```
cnfgen op 10 3 -T or 2
```
or
```
cnfgen php 10 9 -T xor 2
```
throw the same error.

**Comment by MassimoLauria** [comment]
Commit 0cc12ab should fix this. There was some level of escaping missing while adding yet another index to the variables.
