### ISSUE TITLE
Binary k-clique formulas satisfiable for (k-1)-partite graphs

### ISSUE THREAD

**Issue by aoertel** [MassimoLauria/cnfgen#115]
The CNFs generated for the binary k-clique formula are satisfiable for (k-1)-partite complete graphs, which should not be the case, as (k-1)-partite graphs can not contain a clique of size k. For example, the CNF generated by
```
cnfgen kcliquebin 3 complete 3 2
```
has the solution `-1 -2 -3 -4 5 6 7 -8 9`.

**Comment by MassimoLauria** [comment]
Commit 708904f should fix this. It was actually a relatively serious off-by-one error because graph vertices are 1-indexed, and the formula must shift them.
