### ISSUE TITLE
Compatibility with networkx 1.10

### ISSUE THREAD

**Issue by MassimoLauria** [MassimoLauria/cnfgen#29]
Networkx 1.10 clean up the packages for bipartite graphs. In particular
  
  1. many functions go from `networkx.*` to `networkx.bipartite.*` for example the random_bipartite
  2. `complete_bipartite_graph` now sets up the bipartition marking nodes 0 and 1 as in other 
    constructions.

(1) makes our code to break and (2) could allow some code cleanup.

What do you say @marcvinyals ?

**Comment by MassimoLauria** [comment]
This should have been fixed by commit b2d67ff7747d30442a4c8b08b4c0b56eed54abfa
I just access the functions in two different ways.

**Comment by MassimoLauria** [comment]
Uff I think that I went from AttributeError to ImportError at some point. Don't know why... 3e853af5f97e872a4e3ae588660af42334cb38d5 should fix it.

**Comment by marcvinyals** [comment]
Seems to work now. But I set automated testing with both networkx versions in pr #31, it will become unmanageable to do it manually.
