### ISSUE TITLE
Some sections at readthedocs.org are missing

### ISSUE THREAD

**Issue by marcvinyals** [MassimoLauria/cnfgen#52]
It seems that sections 3,4,5 and 7 at https://cnfgen.readthedocs.org are missing. e.g. https://cnfgen.readthedocs.org/en/latest/families.html has (essentially) the same content as https://cnfgen.readthedocs.org/en/latest/index.html

**Comment by MassimoLauria** [comment]
The build process was broken.
Section 6 and 7 are still missing, plus a lot of docstrings, but now everything should be better.
