### ISSUE TITLE
Sparsified Stone formulas

### ISSUE THREAD

**Issue by MassimoLauria** [MassimoLauria/cnfgen#66]
Sent by Jakob Nordstrom:

As I mentioned over dinner yesterday, it might be interesting to check if sparsified Stone formulas are still hard for regular resolution. The idea would be to have 3n stones (or something) for a graph with n vertices, but then chose randomly for every vertex 10 stones (or so) that can be on that vertex. That should decrease the formula size dramatically, and make it possible to run meaningful experiments.

Of course, regardless of whether these formulas are provably hard (or provably easy) for regular resolution it might still be interesting to have them implemented in CNFgen so that one can run experiments on them. So consider this a feature request...

**Comment by marcvinyals** [comment]
Change title to "Sparsified stone formulas"?

**Comment by MassimoLauria** [comment]
Yeah, I had a fight with form autocompletion apparently.

**Comment by MassimoLauria** [comment]
Implemented some time ago
