### ISSUE TITLE
Sparsified stone formulas

### ISSUE THREAD

**Issue by jakobnordstrom** [MassimoLauria/cnfgen#72]
As I mentioned over dinner yesterday, it might be interesting to check if sparsified Stone formulas are still hard for regular resolution. The idea would be to have 3n stones (or something) for a graph with n vertices, but then chose randomly for every vertex 10 stones (or so) that can be on that vertex. That should decrease the formula size dramatically, and make it possible to run meaningful experiments.

Of course, regardless of whether these formulas are provably hard (or provably easy) for regular resolution it might still be interesting to have them implemented in CNFgen so that one can run experiments on them. So consider this a feature request...

**Comment by MassimoLauria** [comment]
The formula now are in the main branch at least  from commit dbbd9a98cc1ce3bcf22d962d00d9de1973766235 . Classic stone formulas haven't been changed but soon they will be implemented as a variant of the sparse ones.
