### ISSUE TITLE
Global option to consistently flip polarities

### ISSUE THREAD

**Issue by jakobnordstrom** [MassimoLauria/cnfgen#75]
Here is a feature request for CNFgen: a global option that flips all literal polarities in a generated formula.

Here is the point: Many state-of-the-art SAT solvers, such as MiniSat, Glucose, and Sat4j, have a default polarity (typically FALSE) when variables are assigned the first time. At times, this could have quite a significant influence on whether formulas are easy or hard. To measure the hardness of the formulas, rather than measuring effects of this heuristic, it will sometimes be interesting to flip the default heuristic. The easiest way of doing this would be simply to generate formulas with all literals flipped.

**Comment by MassimoLauria** [comment]
There is now a "Flip" formula transformation that does it. See commit 060ca4e
