### ISSUE TITLE
Symmetry breaking

### ISSUE THREAD

**Issue by jakobnordstrom** [MassimoLauria/cnfgen#81]
I think it would be good if CNFgen would never do any silent symmetry breaking when generating formulas (except for obvious things such as not generating duplicates of the same clause).

It is well-known that symmetry breaking is an extremely strong tool and can change the properties of many formulas beyond recognition. Thus, this should be something that the user should explicitly request rather than a silent default. (But it would also be nice to have such an option for a formula whenever it is conceivable that CNF gen could help to generate a formula with symmetries broken.)

Also, in, e.g., the SAT competitions it can often be a key component in a well-performing solver to have good symmetry breaking (as was the case in the SAT Competition 2016, for instance), and so this is another reason why one would not want the formula generator to silently do this job.

To take two concrete examples, we know that PHP formulas are hard for resolution and that k-clique formulas over complete (k-1)-partite graphs are hard for tree-like resolution. Therefore, it would be quite confusing for an unsuspecting user, I think, if PHP formulas and k-clique formulas were generated with symmetry breaking by default, so that they would both become trivial for the simplest possible solver implementing unit propagation.

**Comment by MassimoLauria** [comment]
The naive symmetry breaking in the kclique formula can be disabled using `--no-symmetry-breaking`. See commit 2417eff4799eadf75cfe584ccebd4e47a41375d6
