### ISSUE TITLE
Saving of graphs in correct KTHlist format

### ISSUE THREAD

**Issue by jakobnordstrom** [MassimoLauria/cnfgen#86]
Saving of graphs in KTHlist format --- in particular, for bipartite graphs --- should preferably be done in compliance with the KTHlist format and not using the violations of the format accepted by CNFgen as input.

That is, for a bipartite graph only the left side of the bipartition, with the neighbour sets on the right, should be listed.

This is actually relevant as CNFgen can be called to obtain graphs that are used in other contexts, where the assumption is that the KTHlist format specification is followed.

**Comment by MassimoLauria** [comment]
Now CNFgen is very rigid, both in input and in output, regarding KTHlist bipartite graph. 

See commit b93bfc5ecdecbac00861c51b98e679a165d5c631
