### ISSUE TITLE
Upgrade to networkx 2.X

### ISSUE THREAD

**Issue by MassimoLauria** [MassimoLauria/cnfgen#90]
Networkx has changed the API going from 1.X to 2.X release. The two APIs are incompatible.
CNFgen should move to 2.X

See 
https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html

**Comment by marcvinyals** [comment]
Is there something broken you have in mind or is it more of a general check-up? Some tests fail with 2.X, but it is actually the tests themselves that are incompatible, and it is easy to rewrite them to be compatible with both 1.X and 2.X, I can send a PR for that. I found some constructions that are deprecated and will no longer work with 3.X, so it may be a good idea to rewrite these too, but nothing that would immediately fail.

**Comment by alugowski** [comment]
If someone like me wants to try this project on a modern system (Python 3, networkx 2+) then you can install my updates directly from GitHub:

    pip install git+https://github.com/alugowski/cnfgen.git@networkx2#egg=cnfgen

Note you must have networkx already installed due to the funky way this project's `setup.py` works.
