### ISSUE TITLE
Installation breaks on python3

### ISSUE THREAD

**Issue by msoos** [MassimoLauria/cnfgen#98]
Hi,

First of all, great work, thank you so much! I even tweeted about this work, here: https://twitter.com/SoosMate/status/1133097187351715840

This is just a humble enhancement request. In the README, it's best to put a "2" at the end of almost all commands, since the system is for python2. So for example:

```
python setup.py install
```

should become:

```
python2 setup.py install
```

this will fix all installation issues. The same applies to e.g. using `pip` (also should be `pip2`), `easy_install` (should be `easy_install2`), etc.
 
Just so you know, I **really** appreciate your work here, it's amazing stuff. Please let me know if I should make a pull request out of this. I am happy to help, not just complain :) Thanks for the great tool!

**Comment by MassimoLauria** [comment]
Now the software have been upgraded to python3. And REAME file has been fixed.

**Comment by msoos** [comment]
Thanks! And thanks for the software :)

Mate
